export type TileType =
  | "PROPERTY"
  | "RAILROAD"
  | "UTILITY"
  | "CHANCE"
  | "COMMUNITY"
  | "TAX"
  | "CORNER";

export type ColorGroup =
  | "BROWN" // شمال أفريقيا
  | "LIGHT_BLUE" // المغرب العربي
  | "PINK" // بلاد الشام
  | "ORANGE" // العراق والخليج
  | "RED" // الخليج العربي
  | "YELLOW" // مصر الحبيبة (الوادي الجديد، الأقصر، الإسكندرية)
  | "GREEN" // المملكة العربية السعودية
  | "DARK_BLUE" // العواصم الكبرى (أبو ظبي، دبي، القاهرة)
  | "TRANSPORT"
  | "UTILITY"
  | "SPECIAL";

export interface BoardTile {
  index: number;
  id: string;
  nameAr: string;
  nameEn: string;
  country: string;
  countryFlag: string;
  type: TileType;
  colorGroup: ColorGroup;
  price: number; // 0 for special
  baseRent: number;
  rentTiers: [number, number, number, number, number, number]; // [base, 1 house, 2 houses, 3 houses, 4 houses, hotel]
  houseCost: number;
  mortgageValue: number;
  icon?: string;
}

export interface PropertyState {
  ownerId: string;
  houses: number; // 0 to 4 houses, 5 = hotel
  isMortgaged: boolean;
}

export type PropertiesStateMap = Record<number, PropertyState>;

export interface LuckCard {
  id: string;
  titleAr: string;
  titleEn: string;
  descAr: string;
  descEn: string;
  action:
    | "COLLECT_MONEY"
    | "PAY_MONEY"
    | "MOVE_TO"
    | "MOVE_STEPS"
    | "GO_TO_JAIL"
    | "GET_OUT_OF_JAIL"
    | "COLLECT_FROM_PLAYERS";
  amount?: number;
  targetIndex?: number;
  steps?: number;
}

// Full 40 Egyptian & Arab World Bank El Hazz Board Layout
export const BANK_TILES: BoardTile[] = [
  // BOTTOM ROW: 0 to 10 (Right to Left on board)
  {
    index: 0,
    id: "tile-0",
    nameAr: "ابدأ (محطة البداية)",
    nameEn: "GO (Start)",
    country: "عام",
    countryFlag: "🚩",
    type: "CORNER",
    colorGroup: "SPECIAL",
    price: 0,
    baseRent: 0,
    rentTiers: [0, 0, 0, 0, 0, 0],
    houseCost: 0,
    mortgageValue: 0,
    icon: "🟢",
  },
  {
    index: 1,
    id: "tile-1",
    nameAr: "الخرطوم",
    nameEn: "Khartoum",
    country: "السودان",
    countryFlag: "🇸🇩",
    type: "PROPERTY",
    colorGroup: "BROWN",
    price: 60,
    baseRent: 4,
    rentTiers: [4, 20, 60, 180, 320, 450],
    houseCost: 50,
    mortgageValue: 30,
  },
  {
    index: 2,
    id: "tile-2",
    nameAr: "كارت الحظ",
    nameEn: "Chance Card",
    country: "عام",
    countryFlag: "❓",
    type: "CHANCE",
    colorGroup: "SPECIAL",
    price: 0,
    baseRent: 0,
    rentTiers: [0, 0, 0, 0, 0, 0],
    houseCost: 0,
    mortgageValue: 0,
    icon: "❓",
  },
  {
    index: 3,
    id: "tile-3",
    nameAr: "وهران",
    nameEn: "Oran",
    country: "الجزائر",
    countryFlag: "🇩🇿",
    type: "PROPERTY",
    colorGroup: "BROWN",
    price: 80,
    baseRent: 8,
    rentTiers: [8, 40, 100, 300, 450, 600],
    houseCost: 50,
    mortgageValue: 40,
  },
  {
    index: 4,
    id: "tile-4",
    nameAr: "ضريبة دخل",
    nameEn: "Income Tax",
    country: "عام",
    countryFlag: "💸",
    type: "TAX",
    colorGroup: "SPECIAL",
    price: 100,
    baseRent: 100,
    rentTiers: [100, 0, 0, 0, 0, 0],
    houseCost: 0,
    mortgageValue: 0,
    icon: "💸",
  },
  {
    index: 5,
    id: "tile-5",
    nameAr: "مطار القاهرة الدولي",
    nameEn: "Cairo Int. Airport",
    country: "مصر",
    countryFlag: "🇪🇬",
    type: "RAILROAD",
    colorGroup: "TRANSPORT",
    price: 200,
    baseRent: 25,
    rentTiers: [25, 50, 100, 200, 200, 200], // doubles with each transport owned
    houseCost: 0,
    mortgageValue: 100,
    icon: "✈️",
  },
  {
    index: 6,
    id: "tile-6",
    nameAr: "الدار البيضاء",
    nameEn: "Casablanca",
    country: "المغرب",
    countryFlag: "🇲🇦",
    type: "PROPERTY",
    colorGroup: "LIGHT_BLUE",
    price: 100,
    baseRent: 6,
    rentTiers: [6, 30, 90, 270, 400, 550],
    houseCost: 50,
    mortgageValue: 50,
  },
  {
    index: 7,
    id: "tile-7",
    nameAr: "بنك الحظ (صندوق الجماعة)",
    nameEn: "Community Chest",
    country: "عام",
    countryFlag: "🎁",
    type: "COMMUNITY",
    colorGroup: "SPECIAL",
    price: 0,
    baseRent: 0,
    rentTiers: [0, 0, 0, 0, 0, 0],
    houseCost: 0,
    mortgageValue: 0,
    icon: "🎁",
  },
  {
    index: 8,
    id: "tile-8",
    nameAr: "مراكش",
    nameEn: "Marrakech",
    country: "المغرب",
    countryFlag: "🇲🇦",
    type: "PROPERTY",
    colorGroup: "LIGHT_BLUE",
    price: 100,
    baseRent: 6,
    rentTiers: [6, 30, 90, 270, 400, 550],
    houseCost: 50,
    mortgageValue: 50,
  },
  {
    index: 9,
    id: "tile-9",
    nameAr: "تونس العاصمة",
    nameEn: "Tunis",
    country: "تونس",
    countryFlag: "🇹🇳",
    type: "PROPERTY",
    colorGroup: "LIGHT_BLUE",
    price: 120,
    baseRent: 8,
    rentTiers: [8, 40, 100, 300, 450, 600],
    houseCost: 50,
    mortgageValue: 60,
  },
  {
    index: 10,
    id: "tile-10",
    nameAr: "السجن / زيارة فقط",
    nameEn: "Jail / Just Visiting",
    country: "عام",
    countryFlag: "👮",
    type: "CORNER",
    colorGroup: "SPECIAL",
    price: 0,
    baseRent: 0,
    rentTiers: [0, 0, 0, 0, 0, 0],
    houseCost: 0,
    mortgageValue: 0,
    icon: "👮",
  },

  // LEFT COLUMN: 11 to 20 (Bottom to Top)
  {
    index: 11,
    id: "tile-11",
    nameAr: "عمّان",
    nameEn: "Amman",
    country: "الأردن",
    countryFlag: "🇯🇴",
    type: "PROPERTY",
    colorGroup: "PINK",
    price: 140,
    baseRent: 10,
    rentTiers: [10, 50, 150, 450, 625, 750],
    houseCost: 100,
    mortgageValue: 70,
  },
  {
    index: 12,
    id: "tile-12",
    nameAr: "شركة الكهرباء",
    nameEn: "Electric Utility",
    country: "عام",
    countryFlag: "⚡",
    type: "UTILITY",
    colorGroup: "UTILITY",
    price: 150,
    baseRent: 10, // multiplied by dice roll
    rentTiers: [10, 10, 10, 10, 10, 10],
    houseCost: 0,
    mortgageValue: 75,
    icon: "⚡",
  },
  {
    index: 13,
    id: "tile-13",
    nameAr: "دمشق",
    nameEn: "Damascus",
    country: "سوريا",
    countryFlag: "🇸🇾",
    type: "PROPERTY",
    colorGroup: "PINK",
    price: 140,
    baseRent: 10,
    rentTiers: [10, 50, 150, 450, 625, 750],
    houseCost: 100,
    mortgageValue: 70,
  },
  {
    index: 14,
    id: "tile-14",
    nameAr: "بيروت",
    nameEn: "Beirut",
    country: "لبنان",
    countryFlag: "🇱🇧",
    type: "PROPERTY",
    colorGroup: "PINK",
    price: 160,
    baseRent: 12,
    rentTiers: [12, 60, 180, 500, 700, 900],
    houseCost: 100,
    mortgageValue: 80,
  },
  {
    index: 15,
    id: "tile-15",
    nameAr: "مطار دبي الدولي",
    nameEn: "Dubai Int. Airport",
    country: "الإمارات",
    countryFlag: "🇦🇪",
    type: "RAILROAD",
    colorGroup: "TRANSPORT",
    price: 200,
    baseRent: 25,
    rentTiers: [25, 50, 100, 200, 200, 200],
    houseCost: 0,
    mortgageValue: 100,
    icon: "✈️",
  },
  {
    index: 16,
    id: "tile-16",
    nameAr: "بغداد",
    nameEn: "Baghdad",
    country: "العراق",
    countryFlag: "🇮🇶",
    type: "PROPERTY",
    colorGroup: "ORANGE",
    price: 180,
    baseRent: 14,
    rentTiers: [14, 70, 200, 550, 750, 950],
    houseCost: 100,
    mortgageValue: 90,
  },
  {
    index: 17,
    id: "tile-17",
    nameAr: "كارت الحظ",
    nameEn: "Chance Card",
    country: "عام",
    countryFlag: "❓",
    type: "CHANCE",
    colorGroup: "SPECIAL",
    price: 0,
    baseRent: 0,
    rentTiers: [0, 0, 0, 0, 0, 0],
    houseCost: 0,
    mortgageValue: 0,
    icon: "❓",
  },
  {
    index: 18,
    id: "tile-18",
    nameAr: "البصرة",
    nameEn: "Basra",
    country: "العراق",
    countryFlag: "🇮🇶",
    type: "PROPERTY",
    colorGroup: "ORANGE",
    price: 180,
    baseRent: 14,
    rentTiers: [14, 70, 200, 550, 750, 950],
    houseCost: 100,
    mortgageValue: 90,
  },
  {
    index: 19,
    id: "tile-19",
    nameAr: "مسقط",
    nameEn: "Muscat",
    country: "عُمان",
    countryFlag: "🇴🇲",
    type: "PROPERTY",
    colorGroup: "ORANGE",
    price: 200,
    baseRent: 16,
    rentTiers: [16, 80, 220, 600, 800, 1000],
    houseCost: 100,
    mortgageValue: 100,
  },
  {
    index: 20,
    id: "tile-20",
    nameAr: "الاستراحة المجانية",
    nameEn: "Free Parking",
    country: "عام",
    countryFlag: "🅿️",
    type: "CORNER",
    colorGroup: "SPECIAL",
    price: 0,
    baseRent: 0,
    rentTiers: [0, 0, 0, 0, 0, 0],
    houseCost: 0,
    mortgageValue: 0,
    icon: "🅿️",
  },

  // TOP ROW: 21 to 30 (Left to Right)
  {
    index: 21,
    id: "tile-21",
    nameAr: "المنامة",
    nameEn: "Manama",
    country: "البحرين",
    countryFlag: "🇧🇭",
    type: "PROPERTY",
    colorGroup: "RED",
    price: 220,
    baseRent: 18,
    rentTiers: [18, 90, 250, 700, 875, 1050],
    houseCost: 150,
    mortgageValue: 110,
  },
  {
    index: 22,
    id: "tile-22",
    nameAr: "بنك الحظ (صندوق الجماعة)",
    nameEn: "Community Chest",
    country: "عام",
    countryFlag: "🎁",
    type: "COMMUNITY",
    colorGroup: "SPECIAL",
    price: 0,
    baseRent: 0,
    rentTiers: [0, 0, 0, 0, 0, 0],
    houseCost: 0,
    mortgageValue: 0,
    icon: "🎁",
  },
  {
    index: 23,
    id: "tile-23",
    nameAr: "الدوحة",
    nameEn: "Doha",
    country: "قطر",
    countryFlag: "🇶🇦",
    type: "PROPERTY",
    colorGroup: "RED",
    price: 220,
    baseRent: 18,
    rentTiers: [18, 90, 250, 700, 875, 1050],
    houseCost: 150,
    mortgageValue: 110,
  },
  {
    index: 24,
    id: "tile-24",
    nameAr: "الكويت العاصمة",
    nameEn: "Kuwait City",
    country: "الكويت",
    countryFlag: "🇰🇼",
    type: "PROPERTY",
    colorGroup: "RED",
    price: 240,
    baseRent: 20,
    rentTiers: [20, 100, 300, 750, 925, 1100],
    houseCost: 150,
    mortgageValue: 120,
  },
  {
    index: 25,
    id: "tile-25",
    nameAr: "مطار الملك عبد العزيز",
    nameEn: "King Abdulaziz Airport",
    country: "السعودية",
    countryFlag: "🇸🇦",
    type: "RAILROAD",
    colorGroup: "TRANSPORT",
    price: 200,
    baseRent: 25,
    rentTiers: [25, 50, 100, 200, 200, 200],
    houseCost: 0,
    mortgageValue: 100,
    icon: "✈️",
  },
  // EGYPT GROUP (الوادي الجديد، الأقصر، الإسكندرية)
  {
    index: 26,
    id: "tile-26",
    nameAr: "الوادي الجديد",
    nameEn: "New Valley",
    country: "مصر",
    countryFlag: "🇪🇬",
    type: "PROPERTY",
    colorGroup: "YELLOW",
    price: 260,
    baseRent: 22,
    rentTiers: [22, 110, 330, 800, 975, 1150],
    houseCost: 150,
    mortgageValue: 130,
  },
  {
    index: 27,
    id: "tile-27",
    nameAr: "الأقصر",
    nameEn: "Luxor",
    country: "مصر",
    countryFlag: "🇪🇬",
    type: "PROPERTY",
    colorGroup: "YELLOW",
    price: 260,
    baseRent: 22,
    rentTiers: [22, 110, 330, 800, 975, 1150],
    houseCost: 150,
    mortgageValue: 130,
  },
  {
    index: 28,
    id: "tile-28",
    nameAr: "شركة المياه",
    nameEn: "Water Utility",
    country: "عام",
    countryFlag: "💧",
    type: "UTILITY",
    colorGroup: "UTILITY",
    price: 150,
    baseRent: 10,
    rentTiers: [10, 10, 10, 10, 10, 10],
    houseCost: 0,
    mortgageValue: 75,
    icon: "💧",
  },
  {
    index: 29,
    id: "tile-29",
    nameAr: "الإسكندرية",
    nameEn: "Alexandria",
    country: "مصر",
    countryFlag: "🇪🇬",
    type: "PROPERTY",
    colorGroup: "YELLOW",
    price: 280,
    baseRent: 24,
    rentTiers: [24, 120, 360, 850, 1025, 1200],
    houseCost: 150,
    mortgageValue: 140,
  },
  {
    index: 30,
    id: "tile-30",
    nameAr: "اذهب إلى السجن!",
    nameEn: "Go to Jail!",
    country: "عام",
    countryFlag: "🚨",
    type: "CORNER",
    colorGroup: "SPECIAL",
    price: 0,
    baseRent: 0,
    rentTiers: [0, 0, 0, 0, 0, 0],
    houseCost: 0,
    mortgageValue: 0,
    icon: "🚨",
  },

  // RIGHT COLUMN: 31 to 39 (Top to Bottom)
  {
    index: 31,
    id: "tile-31",
    nameAr: "المدينة المنورة",
    nameEn: "Medina",
    country: "السعودية",
    countryFlag: "🇸🇦",
    type: "PROPERTY",
    colorGroup: "GREEN",
    price: 300,
    baseRent: 26,
    rentTiers: [26, 130, 390, 900, 1100, 1275],
    houseCost: 200,
    mortgageValue: 150,
  },
  {
    index: 32,
    id: "tile-32",
    nameAr: "مكة المكرمة",
    nameEn: "Mecca",
    country: "السعودية",
    countryFlag: "🇸🇦",
    type: "PROPERTY",
    colorGroup: "GREEN",
    price: 300,
    baseRent: 26,
    rentTiers: [26, 130, 390, 900, 1100, 1275],
    houseCost: 200,
    mortgageValue: 150,
  },
  {
    index: 33,
    id: "tile-33",
    nameAr: "كارت الحظ",
    nameEn: "Chance Card",
    country: "عام",
    countryFlag: "❓",
    type: "CHANCE",
    colorGroup: "SPECIAL",
    price: 0,
    baseRent: 0,
    rentTiers: [0, 0, 0, 0, 0, 0],
    houseCost: 0,
    mortgageValue: 0,
    icon: "❓",
  },
  {
    index: 34,
    id: "tile-34",
    nameAr: "الرياض",
    nameEn: "Riyadh",
    country: "السعودية",
    countryFlag: "🇸🇦",
    type: "PROPERTY",
    colorGroup: "GREEN",
    price: 320,
    baseRent: 28,
    rentTiers: [28, 150, 450, 1000, 1200, 1400],
    houseCost: 200,
    mortgageValue: 160,
  },
  {
    index: 35,
    id: "tile-35",
    nameAr: "مطار بيروت الدولي",
    nameEn: "Beirut Int. Airport",
    country: "لبنان",
    countryFlag: "🇱🇧",
    type: "RAILROAD",
    colorGroup: "TRANSPORT",
    price: 200,
    baseRent: 25,
    rentTiers: [25, 50, 100, 200, 200, 200],
    houseCost: 0,
    mortgageValue: 100,
    icon: "✈️",
  },
  {
    index: 36,
    id: "tile-36",
    nameAr: "بنك الحظ (صندوق الجماعة)",
    nameEn: "Community Chest",
    country: "عام",
    countryFlag: "🎁",
    type: "COMMUNITY",
    colorGroup: "SPECIAL",
    price: 0,
    baseRent: 0,
    rentTiers: [0, 0, 0, 0, 0, 0],
    houseCost: 0,
    mortgageValue: 0,
    icon: "🎁",
  },
  {
    index: 37,
    id: "tile-37",
    nameAr: "أبو ظبي",
    nameEn: "Abu Dhabi",
    country: "الإمارات",
    countryFlag: "🇦🇪",
    type: "PROPERTY",
    colorGroup: "DARK_BLUE",
    price: 350,
    baseRent: 35,
    rentTiers: [35, 175, 500, 1100, 1300, 1500],
    houseCost: 200,
    mortgageValue: 175,
  },
  {
    index: 38,
    id: "tile-38",
    nameAr: "ضريبة الرفاهية",
    nameEn: "Luxury Tax",
    country: "عام",
    countryFlag: "💎",
    type: "TAX",
    colorGroup: "SPECIAL",
    price: 75,
    baseRent: 75,
    rentTiers: [75, 0, 0, 0, 0, 0],
    houseCost: 0,
    mortgageValue: 0,
    icon: "💎",
  },
  {
    index: 39,
    id: "tile-39",
    nameAr: "القاهرة العاصمة",
    nameEn: "Cairo",
    country: "مصر",
    countryFlag: "🇪🇬",
    type: "PROPERTY",
    colorGroup: "DARK_BLUE",
    price: 400,
    baseRent: 50,
    rentTiers: [50, 200, 600, 1400, 1700, 2000],
    houseCost: 200,
    mortgageValue: 200,
  },
];

export const COLOR_GROUP_DETAILS: Record<
  ColorGroup,
  { nameAr: string; nameEn: string; hex: string; lightHex: string; tileIndices: number[] }
> = {
  BROWN: {
    nameAr: "شمال أفريقيا",
    nameEn: "North Africa",
    hex: "#8B4513",
    lightHex: "#D2691E",
    tileIndices: [1, 3],
  },
  LIGHT_BLUE: {
    nameAr: "المغرب العربي",
    nameEn: "Maghreb",
    hex: "#38bdf8",
    lightHex: "#7dd3fc",
    tileIndices: [6, 8, 9],
  },
  PINK: {
    nameAr: "بلاد الشام",
    nameEn: "Levant",
    hex: "#ec4899",
    lightHex: "#f472b6",
    tileIndices: [11, 13, 14],
  },
  ORANGE: {
    nameAr: "العراق وعُمان",
    nameEn: "Iraq & Oman",
    hex: "#f97316",
    lightHex: "#fb923c",
    tileIndices: [16, 18, 19],
  },
  RED: {
    nameAr: "الخليج العربي",
    nameEn: "Arabian Gulf",
    hex: "#ef4444",
    lightHex: "#f87171",
    tileIndices: [21, 23, 24],
  },
  YELLOW: {
    nameAr: "مصر الحبيبة",
    nameEn: "Egypt",
    hex: "#eab308",
    lightHex: "#facc15",
    tileIndices: [26, 27, 29],
  },
  GREEN: {
    nameAr: "السعودية",
    nameEn: "Saudi Arabia",
    hex: "#22c55e",
    lightHex: "#4ade80",
    tileIndices: [31, 32, 34],
  },
  DARK_BLUE: {
    nameAr: "العواصم الكبرى (القاهرة ودبي وأبوظبي)",
    nameEn: "Metropolises",
    hex: "#2563eb",
    lightHex: "#60a5fa",
    tileIndices: [37, 39],
  },
  TRANSPORT: {
    nameAr: "المطارات الدولية",
    nameEn: "Int. Airports",
    hex: "#64748b",
    lightHex: "#94a3b8",
    tileIndices: [5, 15, 25, 35],
  },
  UTILITY: {
    nameAr: "المرافق العامة",
    nameEn: "Utilities",
    hex: "#a855f7",
    lightHex: "#c084fc",
    tileIndices: [12, 28],
  },
  SPECIAL: {
    nameAr: "خانات خاصة",
    nameEn: "Special Tiles",
    hex: "#71717a",
    lightHex: "#a1a1aa",
    tileIndices: [0, 2, 4, 7, 10, 17, 20, 22, 30, 33, 36, 38],
  },
};

export const LUCK_CARDS: LuckCard[] = [
  {
    id: "luck-1",
    titleAr: "ربح يانصيب بنك الحظ",
    titleEn: "Bank Lottery Win",
    descAr: "مبروك! ربحت في سحب بنك الحظ وحصلت على ١٥٠ جنيه.",
    descEn: "Congratulations! You won the Bank Lottery. Collect 150 EGP.",
    action: "COLLECT_MONEY",
    amount: 150,
  },
  {
    id: "luck-2",
    titleAr: "غرامة سرعة على الطريق الصحراوي",
    titleEn: "Speeding Ticket",
    descAr: "رادارات الطريق رصدت سرعتك! ادفع غرامة ٥٠ جنيه للمرور.",
    descEn: "Speed camera caught you! Pay a 50 EGP fine.",
    action: "PAY_MONEY",
    amount: 50,
  },
  {
    id: "luck-3",
    titleAr: "رحلة طيران إلى القاهرة",
    titleEn: "Fly directly to Cairo",
    descAr: "تذكرة مجانية للذهاب مباشرة إلى القاهرة (إذا مررت على ابدأ اقبض ٢٠٠ جنيه).",
    descEn: "Advance token to Cairo. If you pass GO, collect 200 EGP.",
    action: "MOVE_TO",
    targetIndex: 39,
  },
  {
    id: "luck-4",
    titleAr: "إلى السجن مباشرة!",
    titleEn: "Go Directly to Jail",
    descAr: "صدر أمر قضائي ضدك، اذهب إلى السجن فوراً ولا تمر على محطة ابدأ.",
    descEn: "Go to jail directly. Do not pass GO, do not collect 200.",
    action: "GO_TO_JAIL",
  },
  {
    id: "luck-5",
    titleAr: "كارت إفراج فوري من السجن",
    titleEn: "Get Out of Jail Free",
    descAr: "عفو استثنائي! احتفظ بهذا الكارت للخروج من السجن مجاناً عند الحاجة.",
    descEn: "Keep this card to get out of jail free anytime.",
    action: "GET_OUT_OF_JAIL",
  },
  {
    id: "luck-6",
    titleAr: "عطلة صيفية في الإسكندرية",
    titleEn: "Trip to Alexandria",
    descAr: "الجو بديع في عروس البحر! تحرك مباشرة إلى الإسكندرية.",
    descEn: "Take a trip to Alexandria. Advance token directly.",
    action: "MOVE_TO",
    targetIndex: 29,
  },
  {
    id: "luck-7",
    titleAr: "هدية عيد ميلادك من الأصدقاء",
    titleEn: "Birthday Gift",
    descAr: "عيد ميلاد سعيد! كل لاعب في الطاولة يقدم لك ٢٥ جنيه كهدية.",
    descEn: "It's your birthday! Collect 25 EGP from each player.",
    action: "COLLECT_FROM_PLAYERS",
    amount: 25,
  },
  {
    id: "luck-8",
    titleAr: "إصلاحات وتجديد العقارات",
    titleEn: "Property Maintenance",
    descAr: "الصيانة الدورية لعقاراتك: ادفع ٥٠ جنيه لتصليح المرافق.",
    descEn: "Pay 50 EGP for general property repairs.",
    action: "PAY_MONEY",
    amount: 50,
  },
  {
    id: "luck-9",
    titleAr: "أرباح استثمارية في البورصة",
    titleEn: "Stock Dividends",
    descAr: "ارتفاع أسهم الشركات العربية! اقبض ١٠٠ جنيه أرباح.",
    descEn: "Stocks went up! Collect 100 EGP dividends.",
    action: "COLLECT_MONEY",
    amount: 100,
  },
  {
    id: "luck-10",
    titleAr: "تراجع ٣ خطوات للخلف",
    titleEn: "Move Back 3 Steps",
    descAr: "نسيت أوراقك المهمة! ارجع ٣ خانات إلى الخلف.",
    descEn: "Forgot your documents! Move back 3 spaces.",
    action: "MOVE_STEPS",
    steps: -3,
  },
  {
    id: "luck-11",
    titleAr: "زيارة سياحية للأقصر",
    titleEn: "Visit Luxor Antiquities",
    descAr: "اذهب لزيارة معابد الكرنك ووادي الملوك في الأقصر.",
    descEn: "Advance directly to Luxor.",
    action: "MOVE_TO",
    targetIndex: 27,
  },
  {
    id: "luck-12",
    titleAr: "استرداد ضريبي من الدولة",
    titleEn: "Tax Refund",
    descAr: "مصلحة الضرائب تعيد لك فائض الضرائب: اقبض ٧٥ جنيه.",
    descEn: "Income tax refund! Collect 75 EGP.",
    action: "COLLECT_MONEY",
    amount: 75,
  },
];
